export const pathToArticles = '/articles'
export const pathToNewArticles = '/newpost'
export const pathToUpdateArticles = '/update/:id'
export const pathToMusic = '/music'
export const pathToScience = '/science'
export const pathToLogin = '/login'
export const pathToRegistration = '/registration'